version: '3.8'
services:
  app:
    container_name: discord-ui
    image: discord-ui
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.dev
      target: development
    ports:
      - "5177:${PORT}"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./index.html
        target: /app/index.html
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./tailwind.config.js
        target: /app/tailwind.config.js
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./vite.config.ts
        target: /app/vite.config.ts
    networks:
      - discord-networks-docker
networks:
  discord-networks-docker:
    external: true
